import CryptoKit
import Foundation

/// The device-only symmetric key that protects one account database at rest.
///
/// In production this is a raw key held in the Data Protection Keychain
/// (device-only, non-synchronizable) and handed to SQLCipher to key the
/// connection before any schema access; pages, WAL, rollback journals, and
/// temporary files all inherit that protection, and a file-backed plaintext
/// temp store is prohibited. That keyed-connection wiring belongs to the
/// deferred storage spike (`docs/dependencies/storage.md`, ADR 0003). Here the
/// key is a value type so the store contract and its in-memory fake can be
/// exercised with a synthetic, test-only key, and so the raw bytes have a single
/// typed home rather than being passed around as bare `Data`.
struct DatabaseKey: Sendable {
    /// The byte width of a raw database key (a 256-bit SQLCipher raw key).
    static let rawKeyByteCount = 32

    private let material: Data

    /// Wraps existing raw key material. Returns `nil` if the width is wrong, so a
    /// truncated or empty key can never silently key a database.
    init?(rawKey: Data) {
        guard rawKey.count == DatabaseKey.rawKeyByteCount else { return nil }
        self.material = rawKey
    }

    /// The raw key bytes, for handing to the keyed-connection layer. Callers must
    /// not log or persist them outside the device-only Keychain.
    var rawKey: Data {
        material
    }

    /// Generates a fresh random database key using the system CSPRNG. In
    /// production this is created once per account and sealed into the
    /// device-only Keychain; the raw value never leaves secure storage.
    static func generated() -> DatabaseKey {
        let bytes = SymmetricKey(size: .bits256).withUnsafeBytes { Data(Array($0)) }
        // Force-unwrap is safe: a 256-bit key is exactly `rawKeyByteCount` bytes.
        return DatabaseKey(rawKey: bytes)!
    }
}

/// The identity a cache-envelope payload is sealed under. It is authenticated
/// (not encrypted) additional data, so a sealed payload can never be opened
/// under a different account, provider, or envelope schema version even with the
/// right key — a misfiled or replayed blob fails closed instead of decrypting.
struct CacheEnvelopeContext: Hashable, Sendable {
    /// The account the wrapped payload belongs to. Its provider is bound too, so
    /// a blob is inseparable from the provider that produced it.
    let account: AccountID
    /// The envelope layout version (`ProviderCacheEnvelope.schemaVersion`), so a
    /// payload sealed under one layout can never be opened as another.
    let schemaVersion: Int

    init(account: AccountID, schemaVersion: Int) {
        self.account = account
        self.schemaVersion = schemaVersion
    }
}

enum CacheEnvelopeCipherError: Error, Equatable, Sendable {
    /// The sealed payload could not be opened: wrong key, tampered bytes, or a
    /// context that does not match the one it was sealed under.
    case openFailed
}

/// The versioned generic AEAD that wraps a provider's lossy, decrypted payload
/// (for example Proton CLI JSON) before it ever rests, producing the
/// `lossyApplicationEncrypted` bytes a `ProviderCacheEnvelope` carries. It binds
/// each sealed payload to its account, provider, and envelope schema version so
/// a blob is inseparable from its identity. Provider-native ciphertext (for
/// example Vaultwarden records) is never wrapped by this cipher — it rests as
/// its own lossless bytes — so this type only ever touches already-decrypted,
/// re-sealed provider output.
///
/// The wrapping key is a test-only in-memory key in this workstream; the
/// production cache-envelope key is a device-only Keychain key introduced with
/// the real store. ChaCha20-Poly1305 is used through CryptoKit (an Apple system
/// framework), so no dependency is added.
enum CacheEnvelopeCipher {
    /// A stable format tag folded into the authenticated data, so a future
    /// format revision can never be confused with this one.
    private static let formatVersion: UInt8 = 1

    /// Seals a plaintext payload under `key`, authenticating `context`. A random
    /// per-message nonce is generated by CryptoKit and carried in the combined
    /// output, so identical payloads never seal to identical bytes.
    static func seal(
        _ plaintext: Data,
        key: SymmetricKey,
        context: CacheEnvelopeContext
    ) throws -> Data {
        let sealedBox = try ChaChaPoly.seal(
            plaintext,
            using: key,
            authenticating: authenticatedData(for: context)
        )
        return sealedBox.combined
    }

    /// Opens a sealed payload, verifying `key` and `context`. Throws `openFailed`
    /// on any mismatch or tampering — the cipher fails closed and never returns
    /// unauthenticated bytes.
    static func open(
        _ sealed: Data,
        key: SymmetricKey,
        context: CacheEnvelopeContext
    ) throws -> Data {
        do {
            let box = try ChaChaPoly.SealedBox(combined: sealed)
            return try ChaChaPoly.open(
                box,
                using: key,
                authenticating: authenticatedData(for: context)
            )
        } catch {
            throw CacheEnvelopeCipherError.openFailed
        }
    }

    /// The authenticated additional data: the format version and the context's
    /// provider, account, and schema version, in a fixed length-prefixed
    /// encoding so distinct field boundaries can never collide.
    private static func authenticatedData(for context: CacheEnvelopeContext) -> Data {
        var data = Data()
        data.append(formatVersion)
        appendLengthPrefixed(context.account.provider.rawValue, to: &data)
        appendLengthPrefixed(context.account.rawValue, to: &data)
        var schema = Int64(context.schemaVersion).bigEndian
        withUnsafeBytes(of: &schema) { data.append(contentsOf: $0) }
        return data
    }

    /// Appends a UTF-8 string prefixed by its 4-byte big-endian length, so no
    /// concatenation of two fields can be reparsed as a different pair.
    private static func appendLengthPrefixed(_ string: String, to data: inout Data) {
        let bytes = Data(string.utf8)
        var length = UInt32(bytes.count).bigEndian
        withUnsafeBytes(of: &length) { data.append(contentsOf: $0) }
        data.append(bytes)
    }
}
